import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import './index.css';

// Inject Chrome API Mock for Web Browser Preview Context
if (typeof window !== 'undefined' && (!window.chrome || !window.chrome.storage)) {
  const mockStorage: Record<string, any> = {};
  const mockListeners: Array<(changes: any, areaName: string) => void> = [];

  const initialMockState = {
    workspaces: [
      {
        id: 'ai_research_ws',
        name: 'AI Research Workspace',
        type: 'ai',
        color: '#8b5cf6',
        pinned: false,
        tabIds: [1, 2]
      }
    ],
    tabs: {
      1: {
        id: 1,
        url: 'https://github.com/sushanth-kumar-prog/Loom',
        title: 'Loom Repository',
        domain: 'github.com',
        favIconUrl: 'https://github.githubassets.com/favicons/favicon.svg',
        openedAt: Date.now() - 3600000,
        lastActiveAt: Date.now() - 1800000,
        timeSpentMs: 120000,
        summary: 'Viewing the Loom codebase on GitHub.',
        workspaceId: 'ai_research_ws'
      },
      2: {
        id: 2,
        url: 'https://openrouter.ai/docs',
        title: 'OpenRouter Documentation',
        domain: 'openrouter.ai',
        favIconUrl: 'https://openrouter.ai/favicon.ico',
        openedAt: Date.now() - 3600000,
        lastActiveAt: Date.now() - 600000,
        timeSpentMs: 60000,
        summary: 'Reviewing OpenRouter API documentation.',
        workspaceId: 'ai_research_ws'
      },
      3: {
        id: 3,
        url: 'https://stripe.com/docs',
        title: 'Stripe Documentation',
        domain: 'stripe.com',
        favIconUrl: 'https://stripe.com/favicon.ico',
        openedAt: Date.now() - 1800000,
        lastActiveAt: Date.now() - 300000,
        timeSpentMs: 30000,
        summary: 'Consulting Stripe developer guides.'
      },
      4: {
        id: 4,
        url: 'https://docs.google.com/document/d/1',
        title: 'Google Docs',
        domain: 'docs.google.com',
        favIconUrl: 'https://ssl.gstatic.com/docs/documents/images/kix-favicon7.ico',
        openedAt: Date.now() - 600000,
        lastActiveAt: Date.now(),
        timeSpentMs: 150000,
        summary: 'Writing project documentation.'
      }
    },
    timeline: [
      {
        timestamp: Date.now() - 3600000,
        type: 'visit',
        title: 'Loom Repository',
        url: 'https://github.com/sushanth-kumar-prog/Loom'
      },
      {
        timestamp: Date.now() - 3000000,
        type: 'visit',
        title: 'OpenRouter Documentation',
        url: 'https://openrouter.ai/docs'
      },
      {
        timestamp: Date.now() - 1800000,
        type: 'visit',
        title: 'Stripe Documentation',
        url: 'https://stripe.com/docs'
      },
      {
        timestamp: Date.now() - 600000,
        type: 'visit',
        title: 'Google Docs',
        url: 'https://docs.google.com/document/d/1'
      }
    ],
    apiKey: '',
    apiProvider: 'openrouter',
    ollamaEndpoint: 'http://localhost:11434/api/chat',
    ollamaModel: 'gemma4',
    settings: {
      hibernationTimeoutMins: 30,
      autoHibernationEnabled: true,
      autoProjectDetection: true
    },
    summaryCache: {}
  };

  mockStorage['state'] = JSON.stringify(initialMockState);

  (window as any).chrome = {
    runtime: {
      lastError: null,
      sendMessage: (message: any, callback: any) => {
        console.log("Mock chrome.runtime.sendMessage received:", message);
        if (message.type === 'TRIGGER_GROUPING') {
          setTimeout(() => {
            const state = JSON.parse(mockStorage['state'] || '{}');
            state.workspaces = state.workspaces || [];
            
            // Heuristic mock workspace addition
            if (!state.workspaces.some((w: any) => w.name === 'Heuristic Dev Workspace')) {
              const wsId = 'ai_heuristic_ws';
              state.workspaces.push({
                id: wsId,
                name: 'Heuristic Dev Workspace',
                type: 'ai',
                color: '#10b981',
                pinned: false,
                tabIds: [3, 4]
              });
              state.tabs[3].workspaceId = wsId;
              state.tabs[3].summary = "Viewing Stripe developer documentation.";
              state.tabs[4].workspaceId = wsId;
              state.tabs[4].summary = "Editing project documentation.";
              
              mockStorage['state'] = JSON.stringify(state);
              mockListeners.forEach(listener => listener({ state: { newValue: state } }, 'local'));
            }
            if (callback) callback({ success: true });
          }, 300);
        } else if (message.type === 'CALL_AI') {
          setTimeout(() => {
            if (callback) callback({ content: "Summary of browsing context generated by mock AI." });
          }, 300);
        }
      },
      onMessage: {
        addListener: () => {}
      }
    },
    storage: {
      local: {
        get: (keys: any, callback: any) => {
          if (typeof keys === 'string') {
            callback({ [keys]: mockStorage[keys] ? JSON.parse(mockStorage[keys]) : undefined });
          } else if (Array.isArray(keys)) {
            const res: any = {};
            keys.forEach(k => {
              res[k] = mockStorage[k] ? JSON.parse(mockStorage[k]) : undefined;
            });
            callback(res);
          } else {
            const res: any = {};
            Object.keys(mockStorage).forEach(k => {
              res[k] = JSON.parse(mockStorage[k]);
            });
            callback(res);
          }
        },
        set: (items: any, callback: any) => {
          Object.keys(items).forEach(k => {
            const oldValue = mockStorage[k] ? JSON.parse(mockStorage[k]) : undefined;
            mockStorage[k] = JSON.stringify(items[k]);
            mockListeners.forEach(listener => listener({ [k]: { oldValue, newValue: items[k] } }, 'local'));
          });
          if (callback) callback();
        },
        clear: (callback: any) => {
          Object.keys(mockStorage).forEach(k => delete mockStorage[k]);
          if (callback) callback();
        }
      },
      onChanged: {
        addListener: (listener: any) => {
          mockListeners.push(listener);
        },
        removeListener: (listener: any) => {
          const idx = mockListeners.indexOf(listener);
          if (idx !== -1) mockListeners.splice(idx, 1);
        }
      }
    },
    tabs: {
      query: (queryInfo: any, callback: any) => {
        callback([
          { id: 1, url: 'https://github.com/sushanth-kumar-prog/Loom', title: 'Loom Repository', favIconUrl: 'https://github.githubassets.com/favicons/favicon.svg', discarded: false },
          { id: 2, url: 'https://openrouter.ai/docs', title: 'OpenRouter Documentation', favIconUrl: 'https://openrouter.ai/favicon.ico', discarded: false },
          { id: 3, url: 'https://stripe.com/docs', title: 'Stripe Documentation', favIconUrl: 'https://stripe.com/favicon.ico', discarded: false },
          { id: 4, url: 'https://docs.google.com/document/d/1', title: 'Google Docs', favIconUrl: 'https://ssl.gstatic.com/docs/documents/images/kix-favicon7.ico', discarded: false }
        ]);
      },
      create: (createProperties: any) => {
        console.log("Mock chrome.tabs.create called:", createProperties);
      },
      discard: async (tabId: number) => {
        console.log("Mock chrome.tabs.discard called:", tabId);
        const state = JSON.parse(mockStorage['state'] || '{}');
        if (state.tabs && state.tabs[tabId]) {
          state.tabs[tabId].isHibernated = true;
          mockStorage['state'] = JSON.stringify(state);
          mockListeners.forEach(listener => listener({ state: { newValue: state } }, 'local'));
        }
        return { id: tabId, discarded: true };
      }
    },
    alarms: {
      create: () => {},
      onAlarm: { addListener: () => {} }
    }
  } as any;
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
